# Generated by Django 3.2.9 on 2022-05-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1110010000)),
                ('color', models.CharField(max_length=1110010000)),
            ],
        ),
    ]
